### ISSUE TITLE
PythonFile2's code is all messed up!

### ISSUE THREAD

**Issue by XJN2** [A-Git-hub-User/Python-Files#1]
```
Traceback (most recent call last):
  File "PythonFile2.py", line 16, in <module>
    import PythonFile2
ModuleNotFoundError: No module named 'PythonFile2'
```

I don't know why you tried to do this. You would need an "os" import to restart the program. I would try to fix it myself but I don't have the time on my hands.

**Comment by A-Git-hub-User** [comment]
Whoops, Sorry about that. I'll try to fix it.

**Comment by AGoodPyDev** [comment]
Don't stress it, I noticed this myself and I'm already working on it.
